### ISSUE TITLE
Data Not Pulling Through on Manual Search

### ISSUE THREAD

**Issue by wesleypearson** [alfio-event/Alf.ioBackoffice#63] opened 2024-05-13 23:26 UTC
Issue Description
In the Backoffice app, when manually searching or scanning an event ticket, additional expected data is not being retrieved.

**Environment**
App Version: 1.8.0
iOS Version: 14.4.1
Devices: iPad 10th Gen, iPhone 14 Pro

**Steps to Reproduce**
Open the Backoffice app on either the iPad 10th Gen or iPhone 14 Pro.
Navigate to the ticket scanning section.
Perform a manual search or scan an event ticket barcode.
Observe that the additional data does not appear as expected.

**Expected Behavior**
Upon searching for an event ticket, all related data should be displayed

**Actual Behavior**
The additional data is not being pulled through after a ticket is  searched manually.

**Additional Information**
This issue has been observed consistently across the mentioned devices.

![Screenshot 2024-05-14 at 9 19 46 AM](https://github.com/alfio-event/Alf.ioBackoffice/assets/46010020/1296649d-941f-4541-8cad-2051a1443212)

**Comment by cbellone** [comment] 2024-05-24 15:03
The issue is on the alf.io server. We have already fixed it on the main branch.
The fix will be released as part of the upcoming M5 version

However, in case you can't wait for the new version, I have backported the fix to the [2.0-M4-maintenance](https://github.com/alfio-event/alf.io/tree/2.0-M4-maintenance) branch.
You'll need to build a new version by yourself and deploy it on your server.

**Closed as completed by cbellone** 2024-05-24 15:03 UTC
